name: Apply Terraform

on:
  push:
    paths:
      - pipeline-terraform/**

jobs:

  apply:
    name: Apply Terraform Configuration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
    
      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve