name: Destroy Terraform

on: workflow_dispatch

env:
  AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:

  destroy:
    name: Destroy Terraform Configuration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./pipeline-terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Init Terraform
        run: |
          terraform init
          terraform destroy -auto-approve