name: Validate Terraform

on:
  push:
    paths:
      - pipeline-terraform/**
      - .github/workflows/**

jobs:

  validate:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./pipeline-terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Init and plan Terraform
        run: |
          terraform init
          terraform validate
          terraform fmt
          terraform plan

